version: '3.8'
services:
  kabanus:
    build: .
    container_name: ${CONTAINER_NAME:-kabanus}
    env_file:
      - stack.env
    restart: unless-stopped
    volumes: []
    ports:
      - "${PORT:-8080}:8080"
