services:
  chat-bot:
    build: .
    container_name: ${CONTAINER_NAME:-chat-bot}
    env_file:
      - stack.env
    restart: unless-stopped
    volumes:
      - cifs-volume:/mnt/${CONTAINER_NAME:-chat-bot}
    ports:
      - "${PORT:-8080}:8080"